---
# Variables ##########

- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}-family.yml"

- name: Include Distribution version specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  failed_when: false

- name: Set facts based on defaults  # noqa var-naming
  ansible.builtin.set_fact:
    "{{ item[8:] }}": "{{ lookup('vars', item) }}"
  when:
    - item is match("^default_")
    - vars[item[8:]] is not defined
  with_items: "{{ vars | list }}"

##########

- name: Install system dependencies
  ansible.builtin.package:
    name: "{{ stagesync_dependency_packages }}"
